### PR TITLE
Fixes and Docker image

### PR DESCRIPTION
**Pull request by brumik**
Fixes form #3 and trying to add docker and docker-compose from the help I got.

### CODE REVIEW

**Comment by hellno** [comment]
@brumik this looks awesome, any support / contribution that would help get this done?

**Comment by brumik** [comment]
Hey, I got stuck on the fact that it takes forever (did not finish on my machine in 3 hours) to install inside docker the pip packages. Also not sure how would it affect to build the image and publish it since this is a GPU dependent app and Docker has dubious support at best for deailng with it correctly.

**Comment by hellno** [comment]
Can you share the Dockerfile that you're currently using? I can test / benchmark on my machine

**Comment by brumik** [comment]
@hellno It seems like I lost it :D I will look into this this week and will update you with my results. I will merge this PR with the fixes in it and will open a new one.

**Pull request merged**
